import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';
import 'package:zezo/service/product_service.dart';
import 'package:zezo/service/products_service.dart';
import 'package:zezo/view/bottom_nav/peoduct_details.dart';

class Languages extends Translations {


  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          ""
          "categories": "Categories",
          "status" : "Status",
          "category" : "Category",
          "what_ever_you_want" : "! What ever you want",
          "home": "Home",
          "account_points" : "Account points",
          "orders": "Orders",
          "profile": "Profile",
          "settings": "Settings",
          "logout": "Logout",
          "login": "Login",
          "register": "Register",
          "email": "Email",
          "password": "Password",
          "name": "Name",
          "phone": "Phone",
          "cr": "CR",
          "vat": "VAT",
          "address": "Address",
          "add": "Add",
          "save": "Save",
          "edit": "Edit",
          "delete": "Delete",
          "cancel": "Cancel",
          "Do you want to delete" : "Do you want to delete ",
          "add_address": "Add Address",
          "edit_address": "Edit Address",
          "add_new_address": "Add New Address",
          "edit_new_address": "Edit New Address",
          "address_name": "Address Name",
          "address_details": "Address Details",
          "deliver time" : "Choose deliver time",
          "choose time" : "Choose time",
          "address_type": "Address Type",
          "home_address": "Home Address",
          "work_address": "Work Address",
          "other_address": "Other Address",
          "select_address_type": "Select Address Type",
          "select_address": "Select Address",
          "select_address_first": "Select Address First",
          "best_selling": "Best Selling",
          "new_arrivals": "New Arrivals",
          "wallet": "Wallet",
          "technical_support": "Technical Support",
          "about_us": "About Us",
          "contact_us": "Contact Us",
          "accounting management" : "Accounting management",
          "financial management" : "Financial Management",
          "terms_and_conditions": "Terms and Conditions",
          "privacy_policy": "Privacy Policy",
          "search": "Search",
          "search_for_products": "Search for Products",
          "search_for_categories": "Search for Categories",
          "language": "Language",
          "general management" : "General management",
          "contact sales" : "Contact with Us",
          "who_we_are": "Who We Are?",
          "our_location": "Our Location",
          "shipping_address": "Shipping Address",
          "payment_method": "Payment Method",
          "orders_history": "Orders History",
          "my_official_documents": "My Official Documents",
          "notifications": "Notifications",
          "select_your_favourite_language": "Select your favourite language",
          "ok": "Ok",
          "offers": "Offers",
          "add category": "Add Category",
          "admins": "Admins",
          "go_main_screen" : "Go to main screen for shopping",
          "edit category": "Edit Category",
          "category name": "Category Name",
          "category name ar": "Category Name (Arabic)",
          "category name en": "Category Name (English)",
          "add subcategory": "Add Subcategory",
          "edit subcategory": "Edit Subcategory",
          "subcategory name": "Subcategory Name",
          "subcategory name ar": "Subcategory Name (Arabic)",
          "subcategory name en": "Subcategory Name (English)",
          "add product": "Add Product",
          "brand name" : "Brand name",
          "edit product": "Edit Product",
          "product name": "Product Name",
          "product name ar": "Product Name (Arabic)",
          "product name en": "Product Name (English)",
          "product description": "Product Description",
          "product description ar": "Product Description (Arabic)",
          "product description en": "Product Description (English)",
          "product price": "Product Price",
          "product quantity": "Product Quantity",
          "product image": "Product Image",
          "product category": "Product Category",
          "product subcategory": "Product Subcategory",
          "product brand": "Product Brand",
          "product details" : "Product details",
          "add to bestselling" : "Add to bestselling",
          "remove from bestselling" : "Remove from bestselling",
          "add to unavailable" : "Add to unavailable",
          "remove from unavailable" : "Remove from unavailable",
          "go to cart" : "Go to shopping cart",
          "unavailable product" : "this product unavailable, this action can't complete",
          //Are you sure?
          "are you sure?": "Are you sure?",
          "no": "No",
          "yes": "Yes",
          "cart": "Cart",
          "no_products" : "There is now chosen products, please go to main screen",
          "my_page": "My Page",
          "done_cart_message": "Done, Added to cart successfully",
          "create new admin": "Create New Admin",
          "admin name": "Admin Name",
          "admin email": "Admin Email",
          "admin password": "Admin Password",
          "admin phone": "Admin Phone",
          "admin photo": "Admin Photo",
          "edit admin": "Edit Admin",
          "edit admin photo": "Edit Admin Photo",
          "edit admin name": "Edit Admin Name",
          "edit admin email": "Edit Admin Email",
          "edit admin phone": "Edit Admin Phone",
          "edit admin password": "Edit Admin Password",
          "orders Management": "Orders Management",
          "unavailable_products" : 'Unavailable products',
          "send_message" : "Send Message",
          "No Orders Yet": "No Orders Yet",
          "share app": "Share App",
          "Reset Password": "Reset Password",
          "Edit Profile": "Edit Profile",
          "Order History": "Order History",
          "Name": "Name",
          "Email": "Email",
          "Phone Number": "Phone Number",
          "phone is required": "Phone is required",
          "phone must be valid": "Phone must be valid",
          "email is required": "Email is required",
          "email must be valid": "Email must be valid",
          "all" : "All",
          "please_login" : "you can't complete this action , please login",
          "go_back" : "Go back",
          "checkout" : "Continue",
          "price" : "Price",
          "discount" : "Discount",
          "update category" : "Update Category",
          "no email" : "there is no email address",
          "no tax number" : "there is no Tax number",
          "tax number" : "tax number :",
          "welcome" : "Welcome back !",
          "login to go" : "Login to go",
          "forget password" : "Did you forget password ?",
          "or login" : "-Or login with-",
          "new user" : "New user",
          "welcome new" : "Welcome !",
          "new acc" : "Signup to go",
          "current user" : "Have account already ?",
          "your points" : "Your points now",
          "your gift" : "Your gift is :",
          "reach" : "Reach to 1000 points \n      to get your gift",
          "get gift" : "Get your gift",
          "title" : "Title",
          "body" : "Body",
          "confirm" : "Confirm",
          "deliver to" : "Deliver to",
          "products" : "Products",
          "pieces" : "Pieces",
          "total before tax" : "Total before taxes",
          "deliver" : "Deliver",
          "total with tax" : "Total with tax",
          "confirm order" : "Do you want to confirm order ?",
          "customer name" : "Customer Name: ",
          "customer email" : "Customer Email: ",
          "customer phone" : "Customer Phone: ",
          "other phone" : "Other phone: ",
          "deliver date" : "Deliver Date",
          "total quantity" : "Total Quantity",
          "total price" : "Total Price",
          "order date" : "Order Date",
          "invoice number" : "Invoice Number",
          "sendMessageWhatsApp" : "Send Whats App Message",
          "totalAmountAfterEdit" : "Total With Tax After Edit",
          "clientName" : "Client Name",
          "error" : "Error",
          "typeClientName" : "Please Type Client Name",
          "typeTotalAfter" : "Please Type Total After Edit",
          "stock" : "Stock Management",
          "All categories": "Categories",
          "addStory" : "Add Story",
          "free" : "Free"
        },
        'ar': {
          "free" : "مجاني",
          "stock" : "إدارة المخزون",
          "error" : "خطأ",
          "typeClientName" : "يرجي كتابة اسم العميل",
          "typeTotalAfter" : "يرجي كتابة السعر بعد التعديل",
          "totalAmountAfterEdit" : "المجموع بالضريبة بعد التعديل",
          "clientName" : "اسم العميل",
          "sendMessageWhatsApp" : "ارسال رساله واتساب",
          "invoice number" : "رقم الفاتورة",
          "order date" : "تاريخ الطلب",
          "total price" : "المبلغ الكلي",
          "total quantity" : "مجموع البنود",
          "brand name" : "اسم البراند",
          "status" : "الحالة",
          "All categories": "جميع الأصناف",
          "category" : "الأصناف",
          "what_ever_you_want" : "كل ما تريد !",
          "home": "الرئيسية",
          "account_points" : "نقاط حسابك",
          "orders": "الطلبات",
          "profile": "الملف الشخصي",
          "settings": "الإعدادات",
          "logout": "تسجيل الخروج",
          "login": "تسجيل الدخول",
          "register": "إنشاء حساب",
          "email": "البريد الإلكتروني",
          "password": "كلمة المرور",
          "name": "الاسم",
          "phone": "رقم الجوال",
          "cr": "السجل التجاري",
          "vat": "الرقم الضريبي",
          "address": "العنوان",
          "add": "إضافة",
          "save": "حفظ",
          "edit": "تعديل",
          "delete": "حذف",
          "cancel": "إلغاء",
          "add_address": "إضافة عنوان",
          "edit_address": "تعديل عنوان",
          "add_new_address": "إضافة عنوان جديد",
          "edit_new_address": "تعديل عنوان جديد",
          "address_name": "اسم العنوان",
          "address_details": "تفاصيل العنوان",
          "deliver time" : "اختر موعد التوصيل",
          "address_type": "نوع العنوان",
          "home_address": "المنزل",
          "work_address": "العمل",
          "other_address": "أخرى",
          "select_address_type": "اختر نوع العنوان",
          "select_address": "اختر العنوان",
          "select_address_first": "اختر العنوان أولاً",
          "best_selling": "الأكثر مبيعاً",
          "new_arrivals": "الجديد",
          "choose time" : "اختر موعد",
          "wallet": "المحفظة",
          "technical_support": "الدعم الفني",
          "about_us": "من نحن",
          "go_main_screen" : "اذهب للصفحه الرئيسيه للتسوق الأن",
          "accounting management" : "اداره الحسابات",
          "general management" : "الأداره العامه",
          "contact_us": "تواصل معنا",
          "financial management" : "أدارةالحسابات",
          "terms_and_conditions": "الشروط والأحكام",
          "privacy_policy": "سياسة الخصوصية",
          "search": "بحث",
          "contact sales" : "تواصل معنا",
          "search_for_products": "بحث عن منتجات",
          "search_for_categories": "بحث عن أقسام",
          "language": "اللغة",
          "who_we_are": "من نحن ؟",
          "our_location": "موقعنا",
          "shipping_address": "عنوان الشحن",
          "payment_method": "طريقة الدفع",
          "orders_history": "سجل الطلبات",
          "my_official_documents": "مستنداتي الرسمية",
          "notifications": "الإشعارات",
          "select_your_favourite_language": "اختر لغتك المفضلة",
          "ok": "موافق",
          "offers": "العروض",
          "no_products" : "لا يوجد منتجات مختاره, اذهب للصفحه الرئيسيه للتسوق",
          "add category": "إضافة قسم",
          "edit category": "تعديل قسم",
          "category name": "اسم القسم",
          "category name ar": "اسم القسم (العربية)",
          "category name en": "اسم القسم (الإنجليزية)",
          "add subcategory": "إضافة قسم فرعي",
          "edit subcategory": "تعديل قسم فرعي",
          "subcategory name": "اسم القسم الفرعي",
          "subcategory name ar": "اسم القسم الفرعي (العربية)",
          "subcategory name en": "اسم القسم الفرعي (الإنجليزية)",
          "add product": "إضافة منتج",
          "edit product": "تعديل منتج",
          "product name": "اسم المنتج",
          "product name ar": "اسم المنتج (العربية)",
          "product name en": "اسم المنتج (الإنجليزية)",
          "product description": "وصف المنتج",
          "product description ar": "وصف المنتج (العربية)",
          "product description en": "وصف المنتج (الإنجليزية)",
          "product price": "سعر المنتج",
          "product quantity": "كمية المنتج",
          "product image": "صورة المنتج",
          "product category": "قسم المنتج",
          "product subcategory": "قسم فرعي المنتج",
          "product brand": "ماركة المنتج",
          "product details" : "تفاصيل المنتج",
          "add to bestselling" : "اضافه الي الأعلي مبيعا",
          "remove from bestselling" : "حذف من الأعلي مبيعا",
          "add to unavailable" : "اضافه الي غير المتاحه",
          "remove from unavailable" : "حذف من الغير متاحه",
          "go to cart" : "الذهاب الي عربه التسوق",
          "unavailable product" : "",
          //Are you sure?
          "are you sure?": "هل أنت متأكد؟",
          "no": "لا",
          "yes": "نعم",
          "Do you want to delete" : "هل تريد حذف ",
          "cart": "السلة",
          "my_page": "صفحتي",
          "done_cart_message": "تمت الإضافة إلى السلة بنجاح",
          "create new admin": "إنشاء مشرف جديد",
          "admin name": "اسم المشرف",
          "admin email": "بريد المشرف",
          "admin password": "كلمة مرور المشرف",
          "admin phone": "رقم جوال المشرف",
          "admin photo": "صورة المشرف",
          "edit admin": "تعديل المشرف",
          "edit admin photo": "تعديل صورة المشرف",
          "edit admin name": "تعديل اسم المشرف",
          "edit admin email": "تعديل بريد المشرف",
          "edit admin phone": "تعديل رقم جوال المشرف",
          "edit admin password": "تعديل كلمة مرور المشرف",
          "admins": "المشرفين",
          "orders Management": "إدارة الطلبات",
          "unavailable_products" : "المنتجات الغير متاحه",
          "send_message" : "ارسال رساله",
          "No Orders Yet": "لا يوجد طلبات بعد",
          "share app": "مشاركة التطبيق",
          "Reset Password": "إعادة تعيين كلمة المرور",
          "Edit Profile": "تعديل الملف الشخصي",
          "Order History": "سجل الطلبات",
          "Name": "الاسم",
          "Email": "البريد الإلكتروني",
          "Phone Number": "رقم الجوال",
          "phone is required": "رقم الجوال مطلوب",
          "phone must be valid": "رقم الجوال يجب أن يكون صحيح",
          "email is required": "البريد الإلكتروني مطلوب",
          "email must be valid": "البريد الإلكتروني يجب أن يكون صحيح",
          "all" : "الكل",
          "addStory" : "اضافة حالة",
          "please_login" : "لا يمكن اتمام العمليه\n"
              "يجب تسجيل الدخول",
          "go_back" : "الرجوع",
          "checkout" : "متابعة",
          "price" : "السعر",
          "discount" : "التخفيض",
          "update category" : "تحديث الصنف",
          "no email" : "لا يوجد بريد الكتروني",
          "no tax number" : "لا يوجد رقم ضريبي",
          "tax number" : "الرقم الضريبي:  ",
          "welcome" : "أهلا بعودتك !",
          "login to go" : "سجل دخولك للأستمرار",
          "forget password" : "هل نسيت كلمه السر ؟",
          "or login" : "-او سجل باستخدام-",
          "new user" : "هل انت مستخدم جديد ؟",
          "welcome new" : "أهلا بك ؟",
          "new acc" : "أنشئ حسابك للأستمرار",
          "current user" : "هل لديك حساب بالفعل ؟",
          "your points" : "نقاطك الحاليه",
          "your gift" : "هديتك هي :",
          "reach" : "قم بالوصول الي 1000 نقطه\n          لأستلام هديتك",
          "get gift" : "استلم هديتك",
          "title" : "عنوان الرسالة",
          "body" : "محتوي الرسالة",
          "confirm" : "تأكيد",
          "deliver to" : "توصيل ألي",
          "products" : "المنتجات",
          "pieces" : "قطع",
          "total before tax" : "المجموع قبل الضريبة",
          "deliver" : "توصيل",
          "total with tax" : "المجموع بالضريبة",
          "confirm order" : "هل تريد تاكيد الطلب ؟",
          "customer name" : "اسم العميل: ",
          "customer email" : "البريد الألكتروني للعميل: ",
          "customer phone": "رقم العميل: ",
          "other phone" : "رقم اخر: ",
          "deliver date" : "موعد التوصيل",
        }
      };
}

class LocalController {
  // get device local
  static String getLocal() {
    return Get.deviceLocale!.languageCode;
  }

  // get device local
  static String getLocalCountry() {
    return Get.deviceLocale!.countryCode!;
  }
}
